CryptoMarketCap workshop
strvcom/ios-course-mendelu-2021 pull request #1
Opened 2021-04-16 05:17 UTC by marekslk

The idea is to build `Markets` and `MarketDetail` scenes (View + Store). 
I am not sure about building `ChartView`. I would probably just use it as a "black box".
The idea is that Networking, Services, ErrorView and AsyncImage will be already prepared before we will start building the app.

2021-04-19 11:14 UTC, Pacek requested changes
💯 agree with the plan to only build View + Store ❤️

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Models/Market.swift
> +struct Market: Identifiable, Hashable {
This should be probably named `MarketItem` as it represents one coin and not the whole market.

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ChartView/ChartViewModel.swift
> +    init(values: [Value], minimumValue: Double, maximumValue: Double) {
I would make this an optional init and return `nil` when the `values` array is empty.

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ErrorView.swift
> +                    .padding([.leading, .trailing], 20)
We can use `.horizontal` here

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ErrorView.swift
> +struct ErrorView<Content: View>: View {
We always init it with a button so I would stay away from generics and simplify it so it just takes an action closure.

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ChartView/ChartViewModel.swift
> +
Unnecessary new line here

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemView.swift
> +                    placeholder: {
The placeholder could be provided by default.

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemViewModel.swift
> +        if priceChangePercentage > 19 {
I'd move the `19` magic number to a constant

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketsStore.swift
> +    // Public
I'd move this above the private dependencies

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Services/API/CoingeckoAPI.swift
> +        let url = buildUrl(with: "/coins/markets?vs_currency=czk&order=market_cap_desc&per_page=100&page=1&sparkline=false")
We should use URLComponents to build the url to show best practices

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Services/API/CoingeckoAPI.swift
> +                    guard item.count == 2 else {
Why is 2 an unlucky number? 🤔

2021-04-19 11:14 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Services/Networking/NetworkClient.swift
> +                print("✅✅ \(value)")
Let's use `os_log` instead of printing

2021-04-21 06:52 UTC, marekslk commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemView.swift
> +                    placeholder: {
What exactly do you mean by this please? 🙂

2021-04-21 06:53 UTC, marekslk commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemViewModel.swift
> +        if priceChangePercentage > 19 {
This magic shouldn't be here at all 🙏

2021-04-21 07:30 UTC, marekslk commented on CryptoMarketCap/CryptoMarketCap/Services/API/CoingeckoAPI.swift
> +                    guard item.count == 2 else {
Because of the way API sends data 😓 😅

2021-04-21 08:02 UTC, marekslk commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ChartView/ChartViewModel.swift
> +    init(values: [Value], minimumValue: Double, maximumValue: Double) {
This complicate things a little bit in the View layer. We would need to add some Empty state.

2021-04-21 09:16 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ChartView/ChartViewModel.swift
> +    init(values: [Value], minimumValue: Double, maximumValue: Double) {
OK, then I would `fatalError()` and add a comment that it would have to be handled in a real-world app

2021-04-21 09:18 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemView.swift
> +                    placeholder: {
To have the `placeholder` set with a default argument so we don't have to set it if we're ok with the default gray placeholder

2021-04-21 09:19 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemViewModel.swift
> +        if priceChangePercentage > 19 {
I think the emojis are actually nice touch - people like emojis :D

2021-04-21 09:30 UTC, marekslk commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemViewModel.swift
> +        if priceChangePercentage > 19 {
Ok then, I'll revert this :)

2021-04-21 09:39 UTC, marekslk commented on CryptoMarketCap/CryptoMarketCap/Scenes/Markets/MarketItem/MarketItemView.swift
> +                    placeholder: {
I improved this even more in https://github.com/strvcom/ios-course-mendelu-2021/pull/1/commits/63dd5978114ff55592effb2ab7aa44ec40d0f011 💪

2021-04-21 09:42 UTC, marekslk commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ChartView/ChartViewModel.swift
> +    init(values: [Value], minimumValue: Double, maximumValue: Double) {
https://github.com/strvcom/ios-course-mendelu-2021/pull/1/commits/59a65b76bb460fbaccab3e0d42e134d771f6a3ec

2021-04-21 10:18 UTC, Pacek requested changes
I would integrate SwiftLint via a Mintfile as we have it here for example: https://github.com/strvcom/ios-nfc-treasure-hunt/blob/master/Mintfile

2021-04-21 10:18 UTC, Pacek commented on CryptoMarketCap/CryptoMarketCap/Scenes/Common/ChartView/ChartViewModel.swift
> +        self.lastDate = values.last!.date
Now that we can return `nil`, I'd guard for the `values.last` so we can avoid force unwrapping.

2021-04-22 06:10 UTC, Pacek approved these changes
🍏

2021-04-22 06:42 UTC, merged